# Generated by Django 5.2.11 on 2026-04-01 11:39

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Empresa')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('ativa', models.BooleanField(default=True, verbose_name='Ativa')),
                ('ncad_cartoes', models.IntegerField(default=0, verbose_name='Cad. Cartões (Stone)')),
                ('ncad_ifood', models.IntegerField(default=0, verbose_name='Cad. iFood')),
                ('ncad_mp', models.IntegerField(default=0, verbose_name='Cad. Mercado Pago')),
                ('ncad_outros', models.IntegerField(default=0, verbose_name='Cad. Outros')),
                ('ncad_swfast', models.IntegerField(default=0, verbose_name='Cad. SWFast (PDV)')),
                ('integrado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Integrado com PDV')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'tbl_empresa',
                'ordering': ['descricao'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('ADMIN', 'Administrador (Vê todas as lojas)'), ('OPERADOR', 'Operador (Vê apenas lojas permitidas)')], default='OPERADOR', max_length=20)),
                ('lojas_permitidas', models.ManyToManyField(blank=True, to='core.empresa', verbose_name='Lojas Permitidas para este Operador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data/Hora')),
                ('tipo_acao', models.CharField(choices=[('CRIACAO', 'Criação'), ('ALTERACAO', 'Alteração'), ('EXCLUSAO', 'Exclusão'), ('ESTORNO', 'Estorno'), ('AJUSTE', 'Ajuste Manual'), ('REABERTURA', 'Reabertura de Período')], max_length=20, verbose_name='Tipo de Ação')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo/Tabela')),
                ('objeto_id', models.CharField(max_length=100, verbose_name='ID do Objeto')),
                ('motivo', models.TextField(blank=True, verbose_name='Motivo')),
                ('snapshot_antes', models.JSONField(blank=True, null=True, verbose_name='Snapshot Antes')),
                ('snapshot_depois', models.JSONField(blank=True, null=True, verbose_name='Snapshot Depois')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresa', verbose_name='Loja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-data_hora'],
                'indexes': [models.Index(fields=['modelo', 'objeto_id'], name='core_regist_modelo_a44527_idx'), models.Index(fields=['data_hora'], name='core_regist_data_ho_7ae5be_idx'), models.Index(fields=['usuario'], name='core_regist_usuario_3ed479_idx')],
            },
        ),
    ]
