# Generated by Django 5.2.11 on 2026-04-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: VENDA_REALIZADA, PAGAMENTO_RECEBIDO, COMPRA_REGISTRADA', max_length=50, unique=True, verbose_name='Código do Evento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('modulo_origem', models.CharField(help_text='Ex: CAIXA, ESTOQUE, FINANCEIRO', max_length=50, verbose_name='Módulo de Origem')),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Evento',
                'verbose_name_plural': 'Tipos de Evento',
                'ordering': ['modulo_origem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ContaSintetica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo_classificacao', models.CharField(help_text='Numeração hierárquica. Ex: 1, 1.1, 1.1.1', max_length=20, verbose_name='Código de Classificação')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Conta')),
                ('tipo_conta', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('RECEITA', 'Receita'), ('DESPESA', 'Despesa'), ('CUSTOS', 'Custos e Despesas')], max_length=20, verbose_name='Tipo de Conta')),
                ('nivel', models.PositiveIntegerField(default=1, verbose_name='Nível Hierárquico')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('conta_pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filhas', to='contabilidade.contasintetica', verbose_name='Conta Pai')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_sinteticas', to='core.empresa', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Conta Sintética',
                'verbose_name_plural': 'Contas Sintéticas',
                'ordering': ['codigo_classificacao'],
                'unique_together': {('loja', 'codigo_classificacao')},
            },
        ),
        migrations.CreateModel(
            name='ContaAnalitica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo_reduzido', models.PositiveIntegerField(verbose_name='Código Reduzido')),
                ('codigo_classificacao', models.CharField(help_text='Ex: 1110001, 3110001', max_length=30, verbose_name='Código de Classificação')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Conta')),
                ('natureza_saldo', models.CharField(choices=[('DEVEDOR', 'Devedor'), ('CREDOR', 'Credor'), ('AMBOS', 'Devedor e Credor')], default='DEVEDOR', max_length=10, verbose_name='Natureza do Saldo')),
                ('aceita_lancamento', models.BooleanField(default=True, verbose_name='Aceita Lançamentos')),
                ('data_bloqueio', models.DateField(blank=True, help_text='Não aceita lançamentos com data anterior a esta', null=True, verbose_name='Data de Bloqueio')),
                ('centro_custo', models.BooleanField(default=False, verbose_name='Exige Centro de Custo')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_analiticas', to='core.empresa', verbose_name='Loja')),
                ('conta_sintetica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_analiticas', to='contabilidade.contasintetica', verbose_name='Conta Sintética (Grupo)')),
            ],
            options={
                'verbose_name': 'Conta Analítica',
                'verbose_name_plural': 'Contas Analíticas',
                'ordering': ['codigo_classificacao'],
                'unique_together': {('loja', 'codigo_reduzido')},
            },
        ),
        migrations.CreateModel(
            name='EventoOperacional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_evento', models.DateTimeField(verbose_name='Data/Hora do Evento')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor do Evento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Contabilização'), ('CONTABILIZADO', 'Contabilizado'), ('ERRO', 'Erro na Contabilização')], default='PENDENTE', max_length=20)),
                ('referencia_id', models.CharField(blank=True, help_text='ID do objeto que originou o evento (venda, pedido, etc.)', max_length=255, verbose_name='ID de Referência')),
                ('referencia_modelo', models.CharField(blank=True, help_text='Nome do modelo que originou o evento', max_length=100, verbose_name='Modelo de Referência')),
                ('dados_extras', models.JSONField(blank=True, help_text='Informações adicionais do evento em JSON', null=True, verbose_name='Dados Extras')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('erro_mensagem', models.TextField(blank=True, verbose_name='Mensagem de Erro')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='core.empresa', verbose_name='Loja')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidade.tipoevento', verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Evento Operacional',
                'verbose_name_plural': 'Eventos Operacionais',
                'ordering': ['-data_evento'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(verbose_name='Número do Lançamento')),
                ('data_lancamento', models.DateField(verbose_name='Data do Lançamento')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Registro')),
                ('historico', models.CharField(max_length=500, verbose_name='Histórico')),
                ('tipo', models.CharField(choices=[('NORMAL', 'Normal'), ('CORRECAO', 'Correção/Ajuste'), ('ESTORNO', 'Estorno'), ('FECHAMENTO', 'Fechamento de Período')], default='NORMAL', max_length=20)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='contabilidade.eventooperacional', verbose_name='Evento de Origem')),
                ('lancamento_referencia', models.ForeignKey(blank=True, help_text='Para estornos e correções, aponta ao lançamento original', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='correcoes', to='contabilidade.lancamentocontabil', verbose_name='Lançamento de Referência')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lancamentos', to='core.empresa', verbose_name='Loja')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuário Responsável')),
            ],
            options={
                'verbose_name': 'Lançamento Contábil',
                'verbose_name_plural': 'Lançamentos Contábeis',
                'ordering': ['-data_lancamento', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='ModeloRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição do Relatório')),
                ('tipo', models.CharField(choices=[('DRE', 'Demonstração do Resultado do Exercício'), ('DFC_DOAR', 'DFC / DOAR')], max_length=10, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelos_relatorio', to='core.empresa', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Modelo de Relatório Contábil',
                'verbose_name_plural': 'Modelos de Relatórios Contábeis',
            },
        ),
        migrations.CreateModel(
            name='EstruturaRelatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(help_text='Posição hierárquica. Ex: 001, 001.001', max_length=20, verbose_name='Posição')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Estrutura')),
                ('tipo_calculo', models.IntegerField(choices=[(0, 'Sintética (Soma das contas)'), (1, 'Vinculada a Contas Analíticas'), (2, 'Resultado de Operações'), (3, 'Valor Informado Manualmente'), (4, 'Grupo de Contas DFC/DOAR')], default=0, verbose_name='Tipo de Cálculo')),
                ('operacao', models.IntegerField(choices=[(4, 'Positivo (+)'), (5, 'Negativo (-)'), (6, 'Igual (=)'), (7, '(+/-)')], default=4, verbose_name='Operação')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estruturas', to='contabilidade.modelorelatorio', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Estrutura de Relatório',
                'verbose_name_plural': 'Estruturas de Relatório',
                'ordering': ['posicao'],
                'unique_together': {('modelo', 'posicao')},
            },
        ),
        migrations.CreateModel(
            name='PartidaLancamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], max_length=1, verbose_name='D/C')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('historico_complementar', models.CharField(blank=True, max_length=255, verbose_name='Histórico Complementar')),
                ('centro_custo', models.CharField(blank=True, max_length=50, verbose_name='Centro de Custo')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partidas', to='contabilidade.contaanalitica', verbose_name='Conta Analítica')),
                ('lancamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidade.lancamentocontabil', verbose_name='Lançamento')),
            ],
            options={
                'verbose_name': 'Partida de Lançamento',
                'verbose_name_plural': 'Partidas de Lançamento',
            },
        ),
        migrations.CreateModel(
            name='PeriodoContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveIntegerField(verbose_name='Mês')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('FECHADO', 'Fechado'), ('REABERTO', 'Reaberto para Ajustes')], default='ABERTO', max_length=10)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora do Fechamento')),
                ('data_reabertura', models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Reabertura')),
                ('motivo_reabertura', models.TextField(blank=True, verbose_name='Motivo da Reabertura')),
                ('fechado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_fechados', to=settings.AUTH_USER_MODEL, verbose_name='Fechado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodos', to='core.empresa', verbose_name='Loja')),
                ('reaberto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_reabertos', to=settings.AUTH_USER_MODEL, verbose_name='Reaberto por')),
            ],
            options={
                'verbose_name': 'Período Contábil',
                'verbose_name_plural': 'Períodos Contábeis',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('loja', 'ano', 'mes')},
            },
        ),
        migrations.AddField(
            model_name='lancamentocontabil',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidade.periodocontabil', verbose_name='Período Contábil'),
        ),
        migrations.CreateModel(
            name='RegraContabil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Regra')),
                ('ativa', models.BooleanField(default=True, verbose_name='Regra Ativa')),
                ('ordem', models.PositiveIntegerField(default=1, help_text='Para eventos que geram múltiplos lançamentos', verbose_name='Ordem de Execução')),
                ('conta_credito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_credito', to='contabilidade.contaanalitica', verbose_name='Conta a Creditar')),
                ('conta_debito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='regras_debito', to='contabilidade.contaanalitica', verbose_name='Conta a Debitar')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras_contabeis', to='core.empresa', verbose_name='Loja')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='contabilidade.tipoevento', verbose_name='Tipo de Evento')),
            ],
            options={
                'verbose_name': 'Regra Contábil',
                'verbose_name_plural': 'Regras Contábeis',
                'ordering': ['tipo_evento', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='ComposicaoEstrutura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conta_analitica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidade.contaanalitica', verbose_name='Conta Analítica')),
                ('estrutura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='contabilidade.estruturarelatorio', verbose_name='Estrutura')),
            ],
            options={
                'verbose_name': 'Composição de Estrutura',
                'verbose_name_plural': 'Composições de Estrutura',
                'unique_together': {('estrutura', 'conta_analitica')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lancamentocontabil',
            unique_together={('loja', 'numero')},
        ),
        migrations.AddIndex(
            model_name='eventooperacional',
            index=models.Index(fields=['status'], name='contabilida_status_c5e31a_idx'),
        ),
        migrations.AddIndex(
            model_name='eventooperacional',
            index=models.Index(fields=['tipo_evento', 'data_evento'], name='contabilida_tipo_ev_ed99be_idx'),
        ),
        migrations.AddIndex(
            model_name='eventooperacional',
            index=models.Index(fields=['loja', 'data_evento'], name='contabilida_loja_id_124f49_idx'),
        ),
    ]
