# Generated by Django 5.2.11 on 2026-04-01 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoConta',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tipo de Conta',
                'verbose_name_plural': 'Tipos de Conta',
                'ordering': ['ordem', 'codigo'],
            },
        ),
        migrations.AlterField(
            model_name='contasintetica',
            name='tipo_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contas_sinteticas', to='contabilidade.tipoconta', verbose_name='Tipo de Conta'),
        ),
    ]
