# Generated by Django 5.2.11 on 2026-04-01 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0002_tipoconta_alter_contasintetica_tipo_conta'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateplanoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Restaurante Brasileiro, Pequeno Comercio, etc', max_length=100, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do template e quando usar', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Plano de Contas',
                'verbose_name_plural': 'Templates Plano de Contas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ContaTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_classificacao', models.CharField(max_length=20, verbose_name='Código de Classificação')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Conta')),
                ('tipo_conta', models.CharField(choices=[('ATIVO', 'Ativo'), ('PASSIVO', 'Passivo'), ('RECEITA', 'Receita'), ('CUSTO', 'Custo'), ('DESPESA', 'Despesa')], max_length=20, verbose_name='Tipo de Conta')),
                ('pai_codigo', models.CharField(blank=True, help_text='Deixe vazio se for conta raiz', max_length=20, null=True, verbose_name='Código da Conta Pai')),
                ('nivel', models.PositiveIntegerField(default=1, verbose_name='Nível Hierárquico')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas', to='contabilidade.templateplanoconta', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Conta Template',
                'verbose_name_plural': 'Contas Template',
                'ordering': ['codigo_classificacao'],
                'unique_together': {('template', 'codigo_classificacao')},
            },
        ),
    ]
