# Generated by Django 5.2.11 on 2026-04-02 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0003_templateplanoconta_contatemplate'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contaanalitica',
            unique_together={('loja', 'conta_sintetica', 'codigo_reduzido')},
        ),
    ]
