# Generated by Django 5.2.11 on 2026-04-02 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0004_fix_codigo_reduzido_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='regracontabil',
            options={'ordering': ['tipo_evento', '-ativa'], 'verbose_name': 'Regra Contábil', 'verbose_name_plural': 'Regras Contábeis'},
        ),
        migrations.RemoveField(
            model_name='regracontabil',
            name='conta_credito',
        ),
        migrations.RemoveField(
            model_name='regracontabil',
            name='conta_debito',
        ),
        migrations.RemoveField(
            model_name='regracontabil',
            name='ordem',
        ),
        migrations.CreateModel(
            name='PartidaRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], help_text='Débito (D) ou Crédito (C)', max_length=1, verbose_name='Tipo')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Execução')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contabilidade.contaanalitica', verbose_name='Conta Analítica')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidade.regracontabil', verbose_name='Regra Contábil')),
            ],
            options={
                'verbose_name': 'Partida de Regra',
                'verbose_name_plural': 'Partidas de Regra',
                'ordering': ['regra', 'ordem'],
                'unique_together': {('regra', 'tipo', 'conta')},
            },
        ),
    ]
