# Generated by Django 5.2.11 on 2026-04-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0005_add_partida_regra_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoconta',
            name='natureza',
            field=models.CharField(choices=[('DEVEDORA', 'Devedora (Saldo Devedor)'), ('CREDORA', 'Credora (Saldo Credor)'), ('MISTA', 'Mista (Saldo Devedor ou Credor)')], default='DEVEDORA', help_text='Define se a conta pode ter saldo devedor, credor ou ambos', max_length=20, verbose_name='Natureza da Conta'),
        ),
    ]
