# Generated by Django 5.2.11 on 2026-04-02 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0006_add_natureza_tipoconta'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Ex: VENDA_REALIZADA, PAGAMENTO_RECEBIDO', max_length=50, verbose_name='Código do Evento')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('modulo_origem', models.CharField(help_text='Ex: CAIXA, ESTOQUE, FINANCEIRO', max_length=50, verbose_name='Módulo de Origem')),
            ],
            options={
                'verbose_name': 'Evento Template',
                'verbose_name_plural': 'Eventos Template',
                'ordering': ['modulo_origem', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='TemplateEventoRegra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Restaurante Padrão, Lanchonete, Padaria', max_length=100, verbose_name='Nome do Template')),
                ('descricao', models.TextField(blank=True, help_text='Descrição do template e quando usar', verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Template Evento/Regra',
                'verbose_name_plural': 'Templates Evento/Regra',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='RegraTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Regra')),
                ('ativa', models.BooleanField(default=True, verbose_name='Regra Ativa')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='contabilidade.eventotemplate', verbose_name='Evento')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regras', to='contabilidade.templateeventoregra', verbose_name='Template')),
            ],
            options={
                'verbose_name': 'Regra Template',
                'verbose_name_plural': 'Regras Template',
                'ordering': ['evento', '-ativa'],
            },
        ),
        migrations.AddField(
            model_name='eventotemplate',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='contabilidade.templateeventoregra', verbose_name='Template'),
        ),
        migrations.CreateModel(
            name='PartidaRegraTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('D', 'Débito'), ('C', 'Crédito')], help_text='Débito (D) ou Crédito (C)', max_length=1, verbose_name='Tipo')),
                ('codigo_conta', models.CharField(help_text='Ex: 1.1.1.02.0001 (será resolvido na importação)', max_length=30, verbose_name='Código de Classificação da Conta')),
                ('ordem', models.PositiveIntegerField(default=1, verbose_name='Ordem de Execução')),
                ('regra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas', to='contabilidade.regratemplate', verbose_name='Regra')),
            ],
            options={
                'verbose_name': 'Partida Regra Template',
                'verbose_name_plural': 'Partidas Regra Template',
                'ordering': ['regra', 'ordem'],
                'unique_together': {('regra', 'tipo', 'codigo_conta')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='eventotemplate',
            unique_together={('template', 'codigo')},
        ),
    ]
