# Generated by Django 5.2.11 on 2026-04-02 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidade', '0007_eventotemplate_templateeventoregra_regratemplate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaanalitica',
            name='eh_modelo',
            field=models.BooleanField(default=False, help_text='Marque para incluir essa conta nos templates de importação', verbose_name='É Modelo?'),
        ),
        migrations.AddField(
            model_name='contasintetica',
            name='eh_modelo',
            field=models.BooleanField(default=False, help_text='Marque para incluir essa conta nos templates de importação', verbose_name='É Modelo?'),
        ),
        migrations.AddField(
            model_name='regracontabil',
            name='eh_modelo',
            field=models.BooleanField(default=False, help_text='Marque para incluir essa regra nos templates de importação', verbose_name='É Modelo?'),
        ),
        migrations.AddField(
            model_name='tipoevento',
            name='eh_modelo',
            field=models.BooleanField(default=False, help_text='Marque para incluir esse evento nos templates de importação', verbose_name='É Modelo?'),
        ),
    ]
