# Generated by Django 5.2.11 on 2026-04-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaPagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('fornecedor', models.CharField(blank=True, max_length=255, verbose_name='Fornecedor')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original')),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Pago')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data de Pagamento')),
                ('origem', models.CharField(choices=[('COMPRA', 'Compra/Fornecedor'), ('FOLHA', 'Folha de Pagamento (Importada)'), ('IMPOSTO', 'Imposto/Taxa'), ('MANUAL', 'Inclusão Manual')], default='MANUAL', max_length=20)),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcialmente Pago'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='core.empresa', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Conta a Pagar',
                'verbose_name_plural': 'Contas a Pagar',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Original')),
                ('valor_recebido', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Recebido')),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Saldo')),
                ('data_emissao', models.DateField(verbose_name='Data de Emissão')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento')),
                ('data_recebimento', models.DateField(blank=True, null=True, verbose_name='Data de Recebimento')),
                ('origem', models.CharField(choices=[('VENDA', 'Venda (Automático)'), ('CONCILIACAO', 'Conciliação de Caixa (Automático)'), ('MANUAL', 'Inclusão Manual')], default='VENDA', max_length=20)),
                ('tipo_manual', models.CharField(blank=True, choices=[('VALE', 'Parcelamento de Vale'), ('EMPRESTIMO', 'Empréstimo a Funcionário'), ('OUTROS', 'Outros')], max_length=20, verbose_name='Tipo (para inclusões manuais)')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('PARCIAL', 'Parcialmente Recebido'), ('RECEBIDO', 'Recebido'), ('CANCELADO', 'Cancelado')], default='ABERTO', max_length=20)),
                ('referencia_evento', models.CharField(blank=True, help_text='ID do evento que gerou este título', max_length=255, verbose_name='Referência do Evento')),
                ('forma_pagamento', models.CharField(blank=True, max_length=100, verbose_name='Forma de Pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contas_receber', to='core.empresa', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Conta a Receber',
                'verbose_name_plural': 'Contas a Receber',
                'ordering': ['-data_vencimento'],
            },
        ),
        migrations.CreateModel(
            name='ExtratoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=20, verbose_name='Agência')),
                ('conta', models.CharField(blank=True, max_length=30, verbose_name='Conta')),
                ('data_movimento', models.DateField(verbose_name='Data do Movimento')),
                ('descricao', models.CharField(max_length=500, verbose_name='Descrição/Histórico')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor')),
                ('tipo', models.CharField(choices=[('C', 'Crédito (Entrada)'), ('D', 'Débito (Saída)')], max_length=1, verbose_name='Tipo')),
                ('conciliado', models.BooleanField(default=False, verbose_name='Conciliado')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('conta_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contapagar', verbose_name='Conta a Pagar Vinculada')),
                ('conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.contareceber', verbose_name='Conta a Receber Vinculada')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extratos', to='core.empresa', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Extrato Bancário',
                'verbose_name_plural': 'Extratos Bancários',
                'ordering': ['-data_movimento'],
            },
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['status', 'data_vencimento'], name='financeiro__status_7acc63_idx'),
        ),
        migrations.AddIndex(
            model_name='contapagar',
            index=models.Index(fields=['loja', 'status'], name='financeiro__loja_id_ee93af_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['status', 'data_vencimento'], name='financeiro__status_f45da9_idx'),
        ),
        migrations.AddIndex(
            model_name='contareceber',
            index=models.Index(fields=['loja', 'status'], name='financeiro__loja_id_05ec17_idx'),
        ),
    ]
