# Generated by Django 5.2.11 on 2026-04-01 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_loja', models.CharField(max_length=50)),
                ('nr_abertura', models.CharField(max_length=50)),
                ('vlrsanguia', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor da Sangria')),
                ('sangriadescricao', models.TextField(verbose_name='Descrição da Sangria')),
            ],
            options={
                'verbose_name': 'Sangria',
                'verbose_name_plural': 'Sangrias',
                'db_table': 'tbl_sangria',
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_loja', models.CharField(max_length=50)),
                ('nr_abertura', models.CharField(max_length=50)),
                ('suprim_inicial_cx', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Suprimento Inicial')),
                ('total_trocos_recebidos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Trocos Recebidos')),
                ('sld_caixa_prox_turno', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Saldo p/ Próximo Turno')),
                ('valor_dinheiro_envelope', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor Dinheiro Envelope')),
                ('pagto_tx_entr_pix_escrit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Pgto Taxa/Entrega/PIX/Escritório')),
                ('dif_cont_sld_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Dif. Contagem Saldo Inicial')),
                ('dif_resumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Diferença Resumo')),
                ('tot_vend_resumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Vendas Resumo')),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'db_table': 'tbl_movcaixa',
                'unique_together': {('codigo_loja', 'nr_abertura')},
            },
        ),
        migrations.CreateModel(
            name='ConciliacaoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('codigo_loja', models.CharField(max_length=50, verbose_name='Código da Loja')),
                ('nr_abertura', models.CharField(max_length=50, verbose_name='Nº Abertura')),
                ('data_conciliacao', models.DateField(verbose_name='Data da Conciliação')),
                ('turno', models.CharField(max_length=10, verbose_name='Turno (Dia/Noite)')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Conferência'), ('CONFERIDO', 'Conferido - Sem Divergência'), ('DIVERGENTE', 'Conferido - Com Divergência'), ('AJUSTADO', 'Ajustado via Valores em Trânsito')], default='PENDENTE', max_length=20)),
                ('total_pdv', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total PDV (SWFast)')),
                ('total_importados', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Total Importados (Stone/iFood)')),
                ('diferenca_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Diferença Total')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('contabilizado', models.BooleanField(default=False, help_text='Se os valores em trânsito foram contabilizados', verbose_name='Contabilizado')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_atualizados', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Conciliação de Caixa',
                'verbose_name_plural': 'Conciliações de Caixa',
                'ordering': ['-data_conciliacao'],
                'unique_together': {('codigo_loja', 'nr_abertura')},
            },
        ),
    ]
