# Generated by Django 5.2.11 on 2026-04-02 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacaocaixa',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Referência para a Empresa. Será preenchido gradualmente a partir do codigo_loja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conciliacoes_caixa', to='core.empresa', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='movimentocaixa',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Referência para a Empresa. Será preenchido gradualmente a partir do codigo_loja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_caixa', to='core.empresa', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='sangria',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Referência para a Empresa. Será preenchido gradualmente a partir do codigo_loja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sangrias', to='core.empresa', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='conciliacaocaixa',
            name='codigo_loja',
            field=models.CharField(help_text='Código SWFast da loja (para auditoria)', max_length=50, verbose_name='Código da Loja'),
        ),
        migrations.AlterField(
            model_name='movimentocaixa',
            name='codigo_loja',
            field=models.CharField(help_text='Código SWFast da loja (para auditoria)', max_length=50),
        ),
        migrations.AlterField(
            model_name='sangria',
            name='codigo_loja',
            field=models.CharField(help_text='Código SWFast da loja (para auditoria)', max_length=50),
        ),
    ]
