# Generated by Django 5.2.11 on 2026-04-02 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoIFood',
            fields=[
                ('id_pedido', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('nr_pedido', models.CharField(blank=True, max_length=100, null=True)),
                ('data', models.DateTimeField(blank=True, null=True)),
                ('restaurante', models.CharField(blank=True, max_length=255, null=True)),
                ('id_restaurante', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_itens', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('vlr_pedido_sw', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('formas_pagamento', models.CharField(blank=True, max_length=255, null=True)),
                ('incentivo_ifood', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('origem_cancelamento', models.CharField(blank=True, max_length=255, null=True)),
                ('status_pedido', models.CharField(blank=True, default='CONCLUIDO', max_length=100, null=True)),
                ('conciliado', models.CharField(default='não', max_length=10)),
            ],
            options={
                'verbose_name': 'Pedido iFood',
                'verbose_name_plural': 'Pedidos iFood',
            },
        ),
        migrations.CreateModel(
            name='TransacaoStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stonecode', models.CharField(blank=True, max_length=100, null=True)),
                ('data_venda', models.DateTimeField(blank=True, null=True)),
                ('bandeira', models.CharField(blank=True, max_length=50, null=True)),
                ('produto', models.CharField(blank=True, max_length=100, null=True)),
                ('stone_id', models.CharField(blank=True, max_length=100, null=True)),
                ('qtd_parcelas', models.IntegerField(default=1)),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('desconto_mdr', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('desconto_antecipacao', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('documento', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Transação Stone',
                'verbose_name_plural': 'Transações Stone',
            },
        ),
        migrations.CreateModel(
            name='VendaSWFast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venda', models.CharField(blank=True, max_length=100, null=True)),
                ('forma_pagamento', models.CharField(max_length=100)),
                ('aplicativo', models.CharField(blank=True, max_length=100, null=True)),
                ('operador', models.CharField(blank=True, max_length=100, null=True)),
                ('data_hora_transacao', models.DateTimeField(blank=True, null=True)),
                ('id_pedido_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('codigo_loja', models.CharField(blank=True, max_length=50, null=True)),
                ('chave_composta', models.CharField(max_length=255, unique=True)),
                ('valor_pagamento', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('nr_abertura', models.CharField(blank=True, max_length=50, null=True)),
                ('dthr_abert_cx', models.DateTimeField(blank=True, null=True)),
                ('dthr_encerr_cx', models.DateTimeField(blank=True, null=True)),
                ('conciliado', models.CharField(default='não', max_length=10)),
            ],
            options={
                'verbose_name': 'Venda SWFast',
                'verbose_name_plural': 'Vendas SWFast',
            },
        ),
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100, verbose_name='Forma de Pagamento (Original)')),
                ('especific_form_pgto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificação Interna (Resumo)')),
                ('codigo_loja', models.CharField(blank=True, help_text='Campo legado - será removido após migração para loja_id', max_length=50, null=True, verbose_name='Código da Loja (Legado)')),
                ('aplicativo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Aplicativo/Origem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='core.empresa', verbose_name='Loja')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'tbl_formapagamento',
                'ordering': ['loja', 'aplicativo', 'forma_pagamento'],
                'unique_together': {('loja', 'forma_pagamento', 'aplicativo')},
            },
        ),
    ]
