# Generated by Django 5.2.11 on 2026-02-25 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codigo_loja', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Código da Loja')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da Empresa')),
                ('ncad_ifood', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID da Loja no iFood')),
                ('integrado', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3)),
            ],
        ),
    ]
