# Generated by Django 5.2.11 on 2026-04-02 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('importacoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='loja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='formas_pagamento', to='core.empresa', verbose_name='Loja'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.RunPython(
            code=lambda apps, schema_editor: None,  # Dados vazios, nenhuma migração necessária
            reverse_code=lambda apps, schema_editor: None,
        ),
    ]
