# Generated by Django 5.2.11 on 2026-02-25 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0002_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='codigo_loja',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='nome',
        ),
        migrations.AddField(
            model_name='empresa',
            name='descricao',
            field=models.CharField(default='sem descricao', max_length=255, verbose_name='Descrição da Empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresa',
            name='id_empresa',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ncad_cartoes',
            field=models.IntegerField(default=0, verbose_name='Cad. Cartões'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ncad_mp',
            field=models.IntegerField(default=0, verbose_name='Cad. Mercado Pago'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ncad_outros',
            field=models.IntegerField(default=0, verbose_name='Cad. Outros'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ncad_swfast',
            field=models.IntegerField(default=0, verbose_name='Cad. SWFast'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ncad_ifood',
            field=models.IntegerField(default=0, verbose_name='Cad. iFood'),
        ),
        migrations.AlterModelTable(
            name='empresa',
            table='tbl_empresa',
        ),
    ]
