# Generated by Django 5.2.11 on 2026-04-02 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0002_add_loja_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formapagamento',
            name='codigo_loja',
        ),
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('loja', 'forma_pagamento', 'aplicativo')},
        ),
    ]
