# Generated by Django 5.2.11 on 2026-02-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0003_remove_empresa_codigo_loja_remove_empresa_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(max_length=100, unique=True, verbose_name='Forma de Pagamento (Original)')),
                ('especific_form_pgto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Especificação (Resumo)')),
            ],
            options={
                'verbose_name': 'Forma de Pagamento',
                'verbose_name_plural': 'Formas de Pagamento',
                'db_table': 'tbl_formapagamento',
            },
        ),
        migrations.CreateModel(
            name='Sangria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_loja', models.CharField(max_length=50)),
                ('nr_abertura', models.CharField(max_length=50)),
                ('vlrsanguia', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='Valor da Sangria')),
                ('sangriadescricao', models.TextField(verbose_name='Descrição da Sangria')),
            ],
            options={
                'verbose_name': 'Sangria',
                'verbose_name_plural': 'Sangrias',
                'db_table': 'tbl_sangria',
            },
        ),
        migrations.CreateModel(
            name='MovimentoCaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_loja', models.CharField(max_length=50)),
                ('nr_abertura', models.CharField(max_length=50)),
                ('suprim_inicial_cx', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_trocos_recebidos', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('sld_caixa_prox_turno', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('valor_dinheiro_envelope', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pagto_tx_entr_pix_escrit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dif_cont_sld_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('dif_resumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tot_vend_resumo', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Movimento de Caixa',
                'verbose_name_plural': 'Movimentos de Caixa',
                'db_table': 'tbl_movcaixa',
                'unique_together': {('codigo_loja', 'nr_abertura')},
            },
        ),
    ]
