# Generated by Django 5.2.11 on 2026-04-02 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('importacoes', '0003_remove_codigo_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaswfast',
            name='loja',
            field=models.ForeignKey(blank=True, help_text='Referência para a Empresa. Será preenchido gradualmente a partir do codigo_loja', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendas_swfast', to='core.empresa', verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='vendaswfast',
            name='codigo_loja',
            field=models.CharField(blank=True, help_text='Código SWFast da loja (para auditoria)', max_length=50, null=True),
        ),
    ]
