# Generated by Django 5.2.11 on 2026-02-25 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0004_formapagamento_sangria_movimentocaixa'),
    ]

    operations = [
        migrations.AddField(
            model_name='formapagamento',
            name='aplicativo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Aplicativo'),
        ),
        migrations.AddField(
            model_name='formapagamento',
            name='codigo_loja',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código da Loja'),
        ),
        migrations.AlterField(
            model_name='formapagamento',
            name='forma_pagamento',
            field=models.CharField(max_length=100, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterUniqueTogether(
            name='formapagamento',
            unique_together={('forma_pagamento', 'codigo_loja', 'aplicativo')},
        ),
    ]
