# Generated by Django 5.2.11 on 2026-02-25 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0005_formapagamento_aplicativo_formapagamento_codigo_loja_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoifood',
            name='formas_pagamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='incentivo_ifood',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='pedidoifood',
            name='origem_cancelamento',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
