# Generated by Django 5.2.11 on 2026-02-25 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0006_pedidoifood_formas_pagamento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acesso', models.CharField(choices=[('ADMIN', 'Administrador (Vê todas as lojas)'), ('OPERADOR', 'Operador (Vê apenas lojas permitidas)')], default='OPERADOR', max_length=20)),
                ('lojas_permitidas', models.ManyToManyField(blank=True, to='importacoes.empresa', verbose_name='Lojas Permitidas para este Operador')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuário',
                'verbose_name_plural': 'Perfis de Usuários',
            },
        ),
    ]
