# Generated by Django 5.2.11 on 2026-03-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importacoes', '0007_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoifood',
            name='status_pedido',
            field=models.CharField(blank=True, default='CONCLUIDO', max_length=100, null=True),
        ),
    ]
